#! /bin/sh

ws1=1
ws2=2
ws3=3
ws4=4
ws5=5
ws6=6

pgre -x sxhkd > /dev/null || sxhkd &

bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# [ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
# pgrep -x panel > /dev/null || panel &

# polybar

$HOME/.config/polybar/launch.sh &
